import { useEffect, useState } from 'react';
import { Alert, Button, Dialog, DialogActions, DialogContent, DialogTitle, Divider, MenuItem, Select, Stack, TextField, Typography } from '@mui/material';
import { ProjectData } from '../utils/projectBundle';
import { getProjectMembers, joinProject, ProjectMember, publishProject, removeProjectMember, setProjectMemberRole } from '../utils/collaboration';

interface Props { open: boolean; onClose: () => void; project: ProjectData | null; onProjectShared: (id: string) => void; onProjectJoined: (project: ProjectData) => void; }

export default function CollaborationDialog({ open, onClose, project, onProjectShared, onProjectJoined }: Props) {
  const [code, setCode] = useState('');
  const [shareCodes, setShareCodes] = useState<{ editor?: string; viewer?: string }>({});
  const [members, setMembers] = useState<ProjectMember[]>([]);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const isAdmin = !project?.collaborationRole || project.collaborationRole === 'owner';
  const loadMembers = async () => { if (!project?.sharedProjectId || !isAdmin) return; try { setMembers(await getProjectMembers(project.sharedProjectId)); } catch (e: any) { setError(e.message || 'No se pudieron cargar los miembros.'); } };
  useEffect(() => { if (open) void loadMembers(); }, [open, project?.sharedProjectId]);
  const share = async (role: 'editor' | 'viewer') => { if (!project) return; setLoading(true); setError(''); try { const result = await publishProject(project, role); onProjectShared(result.sharedProjectId); setShareCodes((current) => ({ ...current, [role]: result.inviteCode })); await loadMembers(); } catch (e: any) { setError(e.message || 'No se pudo crear la invitación.'); } finally { setLoading(false); } };
  const join = async () => { setLoading(true); setError(''); try { onProjectJoined(await joinProject(code)); setCode(''); onClose(); } catch (e: any) { setError(e.message || 'No se pudo unir al proyecto.'); } finally { setLoading(false); } };
  const changeRole = async (member: ProjectMember, role: ProjectMember['role']) => { if (!project?.sharedProjectId) return; setLoading(true); setError(''); try { await setProjectMemberRole(project.sharedProjectId, member.user_id, role); await loadMembers(); } catch (e: any) { setError(e.message || 'No se pudo actualizar el permiso.'); } finally { setLoading(false); } };
  const remove = async (member: ProjectMember) => { if (!project?.sharedProjectId || !window.confirm(`¿Quitar a ${member.email || member.user_id} del proyecto?`)) return; setLoading(true); setError(''); try { await removeProjectMember(project.sharedProjectId, member.user_id); await loadMembers(); } catch (e: any) { setError(e.message || 'No se pudo quitar el usuario.'); } finally { setLoading(false); } };

  return <Dialog open={open} onClose={onClose} fullWidth maxWidth="sm"><DialogTitle>Colaboración y permisos</DialogTitle><DialogContent><Typography color="text.secondary" sx={{ mb: 2 }}>Administra quién puede consultar o modificar este proyecto.</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}{isAdmin && <><Stack direction="row" spacing={1} sx={{ mb: 1 }}><Button variant="contained" onClick={() => share('editor')} disabled={!project || loading}>Código de editor</Button><Button variant="outlined" onClick={() => share('viewer')} disabled={!project || loading}>Código de lectura</Button></Stack>{shareCodes.editor && <TextField fullWidth margin="dense" label="Código de editor" value={shareCodes.editor} InputProps={{ readOnly: true }} />}{shareCodes.viewer && <TextField fullWidth margin="dense" label="Código de solo lectura" value={shareCodes.viewer} InputProps={{ readOnly: true }} />}<Divider sx={{ my: 3 }} /><Typography fontWeight={700} sx={{ mb: 1 }}>Miembros del proyecto</Typography>{members.map((member) => <Stack key={member.user_id} direction="row" alignItems="center" spacing={1} sx={{ py: 1 }}><Typography sx={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis' }}>{member.email || member.user_id}</Typography><Select size="small" value={member.role} disabled={member.role === 'owner' || loading} onChange={(event) => void changeRole(member, event.target.value as ProjectMember['role'])}><MenuItem value="owner">Administrador</MenuItem><MenuItem value="editor">Editor</MenuItem><MenuItem value="viewer">Solo lectura</MenuItem></Select>{member.role !== 'owner' && <Button color="error" size="small" onClick={() => void remove(member)} disabled={loading}>Quitar</Button>}</Stack>)}</>}<Divider sx={{ my: 3 }} /><Typography fontWeight={700}>Unirse con un código</Typography><TextField fullWidth margin="normal" label="Código de invitación" value={code} onChange={(event) => setCode(event.target.value)} /><Button onClick={join} disabled={!code.trim() || loading}>Unirme al proyecto</Button></DialogContent><DialogActions><Button onClick={onClose}>Cerrar</Button></DialogActions></Dialog>;
}
